version: '3'

services:
  vue:
    build: 
      context: .
      target: 'develop-stage'
    container_name: template-vue
    ports:
      - 8080:8080
    volumes:
      - ./app/hello-world:/app/hello-world 
      # Link the capyweb folder to the workdir
      - /app/hello-world/node_modules